export const ROUTES = {
  landing: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  home: "/dashboard",
  dashboard: "/dashboard",
  irrigationHistory: "/irrigation-history",
  statistics: "/statistics",
  userManagement: "/user-management",
  userCreate: "/user-management/create",
  regionManagement: "/region-management",
  mapConfiguration: "/map-configuration",
  systemLog: "/system-log",
  authLog: "/auth-log",
  contactSubmissions: "/contact-submissions",
  settings: "/settings",
  profile: "/profile",
  helpCenter: "/help-center",
  superadmin: "/superadmin",
  adminView: "/admin-view",
  cmsTestimonials: "/superadmin/testimonials",
  cmsLocations: "/superadmin/locations",
  cmsPartners: "/superadmin/partners",
} as const;

export const PUBLIC_ROUTES = [ROUTES.landing, ROUTES.login, ROUTES.forgotPassword, ROUTES.resetPassword] as const;
